# Action to build and release the console app
# Repo now has the secret

name: Build and Publish .NET Console App

on:
  push:
    branches:
      - master
      - actions-fix

jobs:
  setup-NET:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
  build-and-publish-NET-app:
    runs-on: windows-latest

    steps:
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ./output

    - name: Publish
      run: dotnet publish --configuration Release --output ./output --self-contained true --runtime win-x64
      
  release-NET-app:
    runs-on: windows-latest

    steps:
    - name: Zip Output Folder
      run: Compress-Archive -Path ./output -DestinationPath ./mediaPlayer.zip
      shell: pwsh

    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
      
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./mediaPlayer.zip
        asset_name: YouTubeDownloader@v${{ github.run_number }}.zip
        asset_content_type: application/zip