# Action to build and release the console app
# Repo now has the secret

name: Build and Publish .NET Console App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --output ./output

    - name: Publish
      run: dotnet publish --configuration Release --output ./output --self-contained true --runtime win-x64
      
    - name: Zip Output Folder
      run: Compress-Archive -Path ./output -DestinationPath ./mediaPlayer.zip
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./mediaPlayer.zip

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./mediaPlayer.zip
        tag_name: 1.0.3
        name: Release 1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}