name: Build and Release (Self-Contained)

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: windows-latest
            
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Set up .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.x'

        - name: Build
          run: dotnet publish --configuration Release --self-contained -r win-x64

        - name: Create Release
          id: create_release
          uses: softprops/action-gh-releases@v1
          with:
            files: |
                releases/YoutubeDownloader
            tag_name: v1.0.0
            title: Release v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}